### PR TITLE
Bugfix HooksListener::isFrontendEnd() for checking Request type not null

### LINKED ISSUE #32: Type Error in alpdesk/alpdesk-parallax/src/Listener/HooksListener.php Line 48
$this->requestStack->getCurrentRequest() can be type of Request or null.

if $this->requestStack->getCurrentRequest() is null than this results into an type error

``` 
"Contao\CoreBundle\Routing\ScopeMatcher::isFrontendRequest(): Argument #1 ($request) must be of type Symfony\Component\HttpFoundation\Request, null given, called in vendor/alpdesk/alpdesk-parallax/src/Listener/HooksListener.php on line 48"
```

### PR DESCRIPTION
**Pull request by arboc**
Fix possible type error

Closes #32

### CODE REVIEW

**Review by xprojects-de — COMMENTED** [review]
@arboc 

following thing:

1. can you use global use statement for Request

```php
use Symfony\Component\HttpFoundation\Request;
```

2. can you change it to early out like

```php
    private function isFrontend(): bool
    {
        if (!$this->requestStack->getCurrentRequest() instanceof Request) {
            return false;
        }

        return $this->scopeMatcher->isFrontendRequest($this->requestStack->getCurrentRequest());

    }
```

**Comment by arboc** [comment]
done

**Review by xprojects-de — COMMENTED** [review]
please check again.
1. early out for better readability as explained
2. Codeformatting
Sorry for being picky :-)

**Comment by arboc** [comment]
done

**Review by xprojects-de — APPROVED** [review]
@arboc Thanks

**Pull request merged**
